server:
  port: 8883

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA:localhost:9092}
    topic:
      actions: actions
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8889/eureka/}