server:
  port: 8882

spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: ${KAFKA:localhost:9092}
    topic:
      actions: actions
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${SERVER_PORT:8081}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USERNAME:test}
    password: ${POSTGRES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8889/eureka/}

resilience4j.circuitbreaker:
  instances:
    kafkaBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
